-- Custom SQL migration file, put your code below! --
INSERT INTO exercises (name, muscle_group, equipment, is_custom, user_id) VALUES
('Barbell Bench Press', 'Chest', 'Barbell', false, NULL),
('Dumbbell Bench Press', 'Chest', 'Dumbbells', false, NULL),
('Incline Bench Press', 'Chest', 'Barbell', false, NULL),
('Decline Bench Press', 'Chest', 'Barbell', false, NULL),
('Push-Up', 'Chest', 'Bodyweight', false, NULL),
('Chest Fly', 'Chest', 'Dumbbells', false, NULL),
('Cable Crossover', 'Chest', 'Cables', false, NULL),
('Pec Deck', 'Chest', 'Machine', false, NULL),
('Pull-Up', 'Back', 'Bodyweight', false, NULL),
('Chin-Up', 'Back', 'Bodyweight', false, NULL),
('Lat Pulldown', 'Back', 'Cable Machine', false, NULL),
('Bent-Over Barbell Row', 'Back', 'Barbell', false, NULL),
('One-Arm Dumbbell Row', 'Back', 'Dumbbell', false, NULL),
('Seated Cable Row', 'Back', 'Cable Machine', false, NULL),
('T-Bar Row', 'Back', 'T-Bar', false, NULL),
('Machine Row', 'Back', 'Machine', false, NULL),
('Deadlift', 'Back', 'Barbell', false, NULL),
('Romanian Deadlift', 'Hamstrings', 'Barbell', false, NULL),
('Sumo Deadlift', 'Glutes', 'Barbell', false, NULL),
('Trap Bar Deadlift', 'Back', 'Trap Bar', false, NULL),
('Face Pull', 'Shoulders', 'Cable Machine', false, NULL),
('Barbell Overhead Press', 'Shoulders', 'Barbell', false, NULL),
('Dumbbell Shoulder Press', 'Shoulders', 'Dumbbells', false, NULL),
('Arnold Press', 'Shoulders', 'Dumbbells', false, NULL),
('Lateral Raise', 'Shoulders', 'Dumbbells', false, NULL),
('Front Raise', 'Shoulders', 'Dumbbells', false, NULL),
('Rear Delt Fly', 'Shoulders', 'Dumbbells', false, NULL),
('Machine Shoulder Press', 'Shoulders', 'Machine', false, NULL),
('Smith Machine Overhead Press', 'Shoulders', 'Smith Machine', false, NULL),
('Shrugs', 'Traps', 'Dumbbells', false, NULL),
('Barbell Shrugs', 'Traps', 'Barbell', false, NULL),
('Squat', 'Quadriceps', 'Barbell', false, NULL),
('Front Squat', 'Quadriceps', 'Barbell', false, NULL),
('Goblet Squat', 'Quadriceps', 'Dumbbell', false, NULL),
('Hack Squat', 'Quadriceps', 'Machine', false, NULL),
('Smith Machine Squat', 'Quadriceps', 'Smith Machine', false, NULL),
('Leg Press', 'Quadriceps', 'Machine', false, NULL),
('Lunge', 'Quadriceps', 'Dumbbells', false, NULL),
('Reverse Lunge', 'Glutes', 'Dumbbells', false, NULL),
('Walking Lunge', 'Quadriceps', 'Dumbbells', false, NULL),
('Bulgarian Split Squat', 'Glutes', 'Dumbbells', false, NULL),
('Step-Up', 'Quadriceps', 'Dumbbells', false, NULL),
('Leg Extension', 'Quadriceps', 'Machine', false, NULL),
('Hamstring Curl', 'Hamstrings', 'Machine', false, NULL),
('Seated Leg Curl', 'Hamstrings', 'Machine', false, NULL),
('Standing Leg Curl', 'Hamstrings', 'Machine', false, NULL),
('Good Morning', 'Hamstrings', 'Barbell', false, NULL),
('Glute Bridge', 'Glutes', 'Bodyweight', false, NULL),
('Hip Thrust', 'Glutes', 'Barbell', false, NULL),
('Cable Kickback', 'Glutes', 'Cable Machine', false, NULL),
('Calf Raise', 'Calves', 'Bodyweight', false, NULL),
('Seated Calf Raise', 'Calves', 'Machine', false, NULL),
('Standing Calf Raise', 'Calves', 'Machine', false, NULL),
('Donkey Calf Raise', 'Calves', 'Machine', false, NULL),
('Bicep Curl', 'Biceps', 'Dumbbells', false, NULL),
('Barbell Curl', 'Biceps', 'Barbell', false, NULL),
('Preacher Curl', 'Biceps', 'Machine', false, NULL),
('Hammer Curl', 'Biceps', 'Dumbbells', false, NULL),
('Cable Curl', 'Biceps', 'Cable Machine', false, NULL),
('Concentration Curl', 'Biceps', 'Dumbbell', false, NULL),
('Incline Dumbbell Curl', 'Biceps', 'Dumbbells', false, NULL),
('Triceps Pushdown', 'Triceps', 'Cable Machine', false, NULL),
('Overhead Triceps Extension', 'Triceps', 'Dumbbells', false, NULL),
('Skullcrusher', 'Triceps', 'Barbell', false, NULL),
('Triceps Kickback', 'Triceps', 'Dumbbells', false, NULL),
('Close-Grip Bench Press', 'Triceps', 'Barbell', false, NULL),
('Dips', 'Triceps', 'Bodyweight', false, NULL),
('Cable Overhead Extension', 'Triceps', 'Cable Machine', false, NULL),
('Rope Pushdown', 'Triceps', 'Cable Machine', false, NULL),
('Crunch', 'Abs', 'Bodyweight', false, NULL),
('Reverse Crunch', 'Abs', 'Bodyweight', false, NULL),
('Hanging Leg Raise', 'Abs', 'Bodyweight', false, NULL),
('Cable Crunch', 'Abs', 'Cable Machine', false, NULL),
('Plank', 'Abs', 'Bodyweight', false, NULL),
('Russian Twist', 'Abs', 'Bodyweight', false, NULL),
('Bicycle Crunch', 'Abs', 'Bodyweight', false, NULL),
('Decline Sit-Up', 'Abs', 'Bodyweight', false, NULL),
('Woodchopper', 'Obliques', 'Cable Machine', false, NULL),
('Side Plank', 'Obliques', 'Bodyweight', false, NULL),
('Pallof Press', 'Core', 'Cable Machine', false, NULL),
('Farmer''s Walk', 'Full Body', 'Dumbbells', false, NULL),
('Kettlebell Swing', 'Full Body', 'Kettlebell', false, NULL),
('Clean and Press', 'Full Body', 'Barbell', false, NULL),
('Snatch', 'Full Body', 'Barbell', false, NULL),
('Turkish Get-Up', 'Full Body', 'Kettlebell', false, NULL),
('Sled Push', 'Legs', 'Sled', false, NULL),
('Sled Pull', 'Legs', 'Sled', false, NULL),
('Power Clean', 'Full Body', 'Barbell', false, NULL),
('Muscle-Up', 'Full Body', 'Bodyweight', false, NULL),
('Medicine Ball Slam', 'Full Body', 'Medicine Ball', false, NULL),
('Reverse Fly', 'Upper Back', 'Dumbbells', false, NULL),
('Chest Dip', 'Chest', 'Bodyweight', false, NULL),
('Incline Push-Up', 'Chest', 'Bodyweight', false, NULL),
('Decline Push-Up', 'Chest', 'Bodyweight', false, NULL),
('Machine Bicep Curl', 'Biceps', 'Machine', false, NULL),
('Leg Adduction', 'Adductors', 'Machine', false, NULL),
('Leg Abduction', 'Abductors', 'Machine', false, NULL),
('Wrist Curl', 'Forearms', 'Dumbbells', false, NULL),
('Reverse Wrist Curl', 'Forearms', 'Dumbbells', false, NULL),
('Cable Lateral Raise', 'Shoulders', 'Cable Machine', false, NULL);
